### ISSUE TITLE
Keypoint ordering

### ISSUE THREAD

**Issue by anjugopinath** [leolyliu/HOI4D-Instructions#10]
I wanted to confirm that the hand keypoint ordering is same as MANO:
<img width="148" alt="image" src="https://github.com/leolyliu/HOI4D-Instructions/assets/4654298/95528483-79d2-4a75-93ca-b6bd673fff4d">

**Comment by leolyliu** [comment]
> I wanted to confirm that the hand keypoint ordering is same as MANO: <img alt="image" width="148" src="https://user-images.githubusercontent.com/4654298/258078998-95528483-79d2-4a75-93ca-b6bd673fff4d.png">

Yes. Our hand pose definition follows HO3D, which is the same as the figure.
