### ISSUE TITLE
HOI4D_depth_video读取的深度图的值不正常

### ISSUE THREAD

**Issue by GitHofee** [leolyliu/HOI4D-Instructions#11]
您好，感谢您提供的[ObjTracking](https://github.com/hoi4d/ObjTracking)的处理代码！我在运行该代码时输出的点云点的个数为0，经检查发现是在读取深度图数据时，读出的内容值均为0～5的整数，形状是(1080, 1920, 3)，请问是什么问题导致的？
以下是运行`np.savetxt("test.txt",np.asarray(depth).reshape(-1,3),fmt="%.2f")`的部分输出结果
![image](https://github.com/leolyliu/HOI4D-Instructions/assets/64160135/117487ac-d928-4be0-83d9-3cc95b680cbe)

**Comment by leolyliu** [comment]
Hi, GitHofee:
A depth image is an uint16 array with shape (1080, 1920).

**Comment by GitHofee** [comment]
感谢您的回复！我们发现是我们忘记对视频进行解码，直接做了帧切割的问题，运行decode.py对视频解码之后得到的depth结果正常了，谢谢！
