### ISSUE TITLE
what is "shift_rgb"

### ISSUE THREAD

**Issue by zjchenCode** [leolyliu/HOI4D-Instructions#14]
about ”https://github.com/hoi4d/ObjTracking“

![image](https://github.com/leolyliu/HOI4D-Instructions/assets/119160944/64415813-e9c5-46f9-817d-c5081d88ec9c)

I wonder, how the "shift_rgb" folder in Code ”process_BundleTrack_data.py" got.
@leolyliu

**Comment by leolyliu** [comment]
Hi WASEDACHENZIJIAN,
The "shift_rgb" is our released RGB image folder.
