### ISSUE TITLE
How to obtain the 'th_trans' values for the MANO model

### ISSUE THREAD

**Issue by Toytiny** [leolyliu/HOI4D-Instructions#17]
Hi,

Great work! How do you obtain the 'hand_info['trans']' during annotation? To my knowledge, the translation vector of the hand should be a part of the 'theta' parameter. Did you also optimize this translation vector?

**Comment by leolyliu** [comment]
Hi Toytiny,

We have jointly optimized the translation vector and 48D rotations via the hand pose annotation process mentioned in our paper. Our loss functions are defined in Equation 1 and 2, and details are introduced in the appendix. Hope it can help you.
