### ISSUE TITLE
depth scale factor

### ISSUE THREAD

**Issue by viorik** [leolyliu/HOI4D-Instructions#20]
Apologies if I missed this detail. Is there a scale factor applied to the depth videos? In a video that I loaded, I see values between 0 and 7999.

**Comment by leolyliu** [comment]
Hi viorik,

The depth scale is 1000. To construct depth/RGBD videos, please refer to Line 66-67 in prepare_4Dseg/scene2frame.py.

**Comment by viorik** [comment]
Thank you for the quick reply, this answers my question.
