### ISSUE TITLE
Is this dataset  contains 3D keypoints of hands?

### ISSUE THREAD

**Issue by renyuanzhe** [leolyliu/HOI4D-Instructions#22]
should we caculate it by ourselves?

**Comment by leolyliu** [comment]
Hi renyuanzhe,

Please refer to the code at https://github.com/leolyliu/HOI4D-Instructions?tab=readme-ov-file#human-hand-pose. The "kps3d" denotes 3D hand keypoints in the camera coordinate system.

**Comment by renyuanzhe** [comment]
if use the camera poses in https://github.com/leolyliu/HOI4D-Instructions?tab=readme-ov-file#3d-static-scene-panoptic-segmentation, could i transforms the 3D hand keypoints in the camera coordinate system to 3D hand keypoints in the world coordinate

**Comment by kurumi715** [comment]
if use the camera poses in https://github.com/leolyliu/HOI4D-Instructions?tab=readme-ov-file#3d-static-scene-panoptic-segmentation, could i transforms the 3D hand keypoints in the camera coordinate system to 3D hand keypoints in the world coordinate

**Comment by leolyliu** [comment]
> if use the camera poses in https://github.com/leolyliu/HOI4D-Instructions?tab=readme-ov-file#3d-static-scene-panoptic-segmentation, could i transforms the 3D hand keypoints in the camera coordinate system to 3D hand keypoints in the world coordinate

Yes.
