### ISSUE TITLE
Is this dataset contains Intrinsics or Extrinsics of each camera frame?

### ISSUE THREAD

**Issue by renyuanzhe** [leolyliu/HOI4D-Instructions#23]
I would like to know the camera pose of each frames, thankyou

**Comment by leolyliu** [comment]
Hi renyuanzhe,

The camera intrinsics are released at https://drive.google.com/file/d/1mQaPw_dVLYE31BM3_2M_gHoo_ufAJ6kw/view?usp=sharing. For camera pose, please refer to https://github.com/leolyliu/HOI4D-Instructions?tab=readme-ov-file#3d-static-scene-panoptic-segmentation.
