### ISSUE TITLE
Inconsistency in annotation form

### ISSUE THREAD

**Issue by liy1shu** [leolyliu/HOI4D-Instructions#3]
Hi, I've noticed that action annotation have different keys in different datapoints:

In most samples, the annotation of action events is defined in "events": [{"startTime":,"endTime":, }], which is the same as specified in the instructions file.

However, in some datapoints(for example, "ZY20210800003/H3/C13/N39/S140/s04/T1/"), the annotation is given in "markResult":{"marks":[{"hdTimeStart":,"hdTimeEnd":}]. There are dozens of datapoints annotated like this. FYI, I download the dataset from Baiduyun link.

I'm a little bit confused and wonder if it's a mistake or if I understood it wrong.

Could you check it please? Thanks, looking forward to your reply.

**Comment by leolyliu** [comment]
Hi liy1shu,
I'm sorry for the ambiguity of data definition. The action annotation is stored in "markResult" for some videos. The usage for these annotations is the same as which for the annotation stored in "events".
We recommend to use the data packaged in our ActionSeg Challenge (https://www.hoi4d.top/).
