### ISSUE TITLE
4D semantic segmentation annotations

### ISSUE THREAD

**Issue by cdforigua05** [leolyliu/HOI4D-Instructions#4]
I was wondering if you could help me with some questions regarding the dataset, precisely the 4D semantic segmentation benchmark.

I followed the instructions in the README.md in the HOID4D-Instructions repository. But I'm having some issues generating the 4D semantic segmentation annotations.

- what is the data_2Dseg_dir used in prepare_4Dseg/prepare_4Dseg_dataset.py (lines 12 & 88)? I downloaded the data from [here](https://hoi4d.github.io/) and organized it as established in the README.MD file. However, I do not know where is the refine_2Dseg folder. I changed the refine_2Dseg for the 2Dseg folder that contains the shift_mask folder instead of the mask folder. Is that correct?

- In prepare_4Dseg/scene2frame.py (line 137), the code reads label3d_path. However, those label.txt files are not inside the 3Dseg folder. So I'm having an error because I can't find those files. Where I can find those files to generate the 4D semantic segmentation annotations.

Thank you very much for your time and collaboration.

**Comment by leolyliu** [comment]
We are sorry for the trouble caused by the missing files. Could you please download the 4D semantic segnemtation data from the link [SemSeg Challenge Data](https://onedrive.live.com/?authkey=%21AIEicWQaoZnF4x4&id=12E5C3DBEFFD0594%21291&cid=12E5C3DBEFFD0594) on our [HOI4D Challenge](http://www.hoi4d.top/) website directly?

**Comment by QiueY514** [comment]
> Hi cdforigua05,
> 
> We are sorry for the trouble caused by the missing files. Could you please download the 4D semantic segnemtation data from the link [SemSeg Challenge Data](https://onedrive.live.com/?authkey=%21AIEicWQaoZnF4x4&id=12E5C3DBEFFD0594%21291&cid=12E5C3DBEFFD0594) on our [HOI4D Challenge](http://www.hoi4d.top/) website directly?

Hi, I also have the same issue: (1) what is the data_2Dseg_dir used in prepare_4Dseg/prepare_4Dseg_dataset.py, and (2) I can't find label3d_path. And I can't access your provided `SemSeg Challenge Data` link: 
![QQ截图20240604151426](https://github.com/leolyliu/HOI4D-Instructions/assets/141099759/d4d53790-66b4-4fa7-869a-9110d4c9d870)

Looking forward to your reply, thanks!
