### ISSUE TITLE
Visualization code

### ISSUE THREAD

**Issue by cdforigua05** [leolyliu/HOI4D-Instructions#5]
Hi,
I'm interested in using the HOI4D Dataset in my research. Can you provide your visualization code for the Category-Level Object and Part Pose Tracking and 4D Point Cloud Videos Semantic Segmentation benchmarks? Precisely, I want to visualize the annotations of those benchmarks. 

Thank you so much for your work and collaboration!

**Comment by leolyliu** [comment]
Hi cdforigua05,
Please refer to the codes from "Human-object Interaction RGB-D Videos", "Object CAD Models", "4D Dynamic Scene Panoptic Segmentation" and "Category-level Object Pose" in this repository.
