### ISSUE TITLE
测试数据

### ISSUE THREAD

**Issue by huihui0613** [leolyliu/HOI4D-Instructions#6]
您好，非常感谢您提供的数据处理代码！我最近在关注HOI4D的object challenge，但是并没有看见网站上有公布关于位姿跟踪的测试数据集，请问是我哪里有疏忽吗？

**Comment by leolyliu** [comment]
Hi huihui0613,

I am sorry for the missed data of the Objpose Challenge. We are going to update the "Objpose Challenge Data" link.
As an alternative solution, we recommend to download data from "RGB Video", "Depth Video", "CAD Model", "Annotations" and "Camera Parameters" and then process the data with the relevant codes from this repository.

**Comment by huihui0613** [comment]
> 

非常感谢你的回答~

**Comment by huihui0613** [comment]
> Hi huihui0613,
> 
> I am sorry for the missed data of the Objpose Challenge. We are going to update the "Objpose Challenge Data" link. As an alternative solution, we recommend to download data from "RGB Video", "Depth Video", "CAD Model", "Annotations" and "Camera Parameters" and then process the data with the relevant codes from this repository.

![image](https://github.com/leolyliu/HOI4D-Instructions/assets/115716973/1e7c49b2-f1f2-4f41-b187-efdee1702195)
我下载的就是官方网站链接中的数据集，但是我发现这里面只有训练数据，并没有测试数据

**Comment by leolyliu** [comment]
The test set of HOI4D is specified by the file "testset.txt" in this repository. For the Objpose Challenge, only rigid categories in the test set are included in the challenge.

**Comment by huihui0613** [comment]
> The test set of HOI4D is specified by the file "testset.txt" in this repository. For the Objpose Challenge, only rigid categories in the test set are included in the challenge.

![image](https://github.com/leolyliu/HOI4D-Instructions/assets/115716973/6b67cad3-51fe-44f8-9dd5-bc55be6d137a)
![捕获](https://github.com/leolyliu/HOI4D-Instructions/assets/115716973/3075deb1-ad4a-4f18-ac05-f57de8b3c79e)
以刚体马克杯为例，我并没有在数据集中找到对应的测试列表

**Comment by leolyliu** [comment]
We have re-uploaded the files of [Objpose Challenge](https://1drv.ms/f/s!ApQF_e_bw-USgloZ0D9xGqUa0r0V?e=TmQPiD).

**Comment by huihui0613** [comment]
真的非常感谢你不厌其烦的解答！非常感谢！

**Comment by GitHofee** [comment]
> We have re-uploaded the files of [Objpose Challenge](https://1drv.ms/f/s!ApQF_e_bw-USgloZ0D9xGqUa0r0V?e=TmQPiD).

您好，这个链接里的测试集每个视频只有第一帧有object pose的ground truth，无法用来测试模型性能。请问可以release所有帧的gt pose吗？
